### ISSUE TITLE
Node REPL with watch/autoreload for a build config?

### ISSUE THREAD

**Issue by gnl** [cljs/tool#21]
Say I have a build config called main, it'd be nice to be able to do `cljs repl main` and it would build main, launch the repl and set it to watch for changes - I couldn't make this work manually.

**Comment by shaunlebron** [comment]
This is likely not something I can support.  I don't know much about it, but this is what I was able to find on the subject:

- https://github.com/clojure/tools.namespace#reloading-code-motivation
- https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel

**Comment by gnl** [comment]
Thank you, I had some trouble making the Node+Figwheel thing work, but I'll look into it again.

What I was thinking of was this:
https://clojurescript.org/guides/quick-start#node.js-repl

It looks like it should be doing what I was looking for (what with the :watch option and everything), but the documentation isn't too great and I couldn't make that incantation work either, so I was hoping that maybe you possessed the secret knowledge it requires. :)

**Comment by shaunlebron** [comment]
Ah, didn't realize it already had the `:watch` option.  will look

**Comment by shaunlebron** [comment]
Sorry for delay.  I read through the browser repl section of quick start (`:watch` behavior is same as node repl):
https://clojurescript.org/guides/quick-start#browser-repl

`(cljs.repl/repl ... :watch ...)` will spin off a watch task in another thread, meaning you have to `tail -f out/watch.log` to see its output.  We'd have to branch from this behavior to support the same pretty-printing of output we do in our `cljs watch` task.  I'll keep thinking about this.

For now, I added the ability to have `cljs repl main` run alongside `cljs watch main`, which you currently have to run separately.  I tested it out and you can do `(require 'my.ns :reload)` in the REPL to load changes after recompilation completes. 👍

fixed: https://github.com/cljs/tool/commit/a278e6db3fcf72ee5fb4bb5bbe123fd2a5615ecf

**Comment by gnl** [comment]
Sounds good, but I can't seem to get this to work, I'm getting this when trying to require the namespace:

```
cljs.user=> (require 'foo.testns :reload)
java.lang.IllegalArgumentException: Namespace foo.testns does not exist
	at cljs.closure$source_for_namespace.invokeStatic(closure.clj:689)
	at cljs.repl$load_namespace.invokeStatic(repl.cljc:191)
	at cljs.repl$load_dependencies.invokeStatic(repl.cljc:215)
	at cljs.repl$evaluate_form.invokeStatic(repl.cljc:487)
	at cljs.repl$eval_cljs.invokeStatic(repl.cljc:604)
	at cljs.repl$eval_cljs.invoke(repl.cljc:591)
	at cljs.repl$repl_STAR_$read_eval_print__5619.invoke(repl.cljc:855)
	at cljs.repl$repl_STAR_$fn__5625$fn__5634.invoke(repl.cljc:896)
	at cljs.repl$repl_STAR_$fn__5625.invoke(repl.cljc:895)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1178)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:831)
	at cljs.repl$repl.invokeStatic(repl.cljc:975)
	at cljs.repl$repl.doInvoke(repl.cljc:907)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at user$eval29.invokeStatic(repl.clj:7)
	at user$eval29.invoke(repl.clj:6)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$script_opt.invokeStatic(main.clj:335)
	at clojure.main$script_opt.invoke(main.clj:330)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

My cljs.edn:

```
{:cljs-version "1.9.521"
 :builds       {:foo     {:src      ["foo"]
                          :compiler {:output-to     "foo.js"
                                     :output-dir    "target/foo"
                                     :target        :nodejs
                                     :main          "foo.testns"
                                     :optimizations :none
                                     :source-map    true}}}}
```

The script:
```
(ns foo.testns
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)

(defn something [x]
  (inc x))

(defn -main [& args]
  (println "foo"))

(set! *main-cli-fn* -main)
```

I first run `cljs watch foo` and while it's running I launch the repl with `rlwrap cljs repl foo`. rlwrap doesn't make a difference and neither does removing the :reload option. I confirmed that the version I have installed is a278e6db3fcf72ee5fb4bb5bbe123fd2a5615ecf. Am I missing something? Thanks

**Comment by gnl** [comment]
Just deleted my previous comment as I kinda got this to to work, but not quite - it loads the namespace correctly and all, but doesn't reload on recompile.

My cljs.edn:

```
{:cljs-version "1.9.521"
 :builds       {:foo     {:src      ["foo"]
                          :compiler {:output-to     "foo.js"
                                     :output-dir    "target/foo"
                                     :target        :nodejs
                                     :main          "bar.testns"
                                     :optimizations :none
                                     :source-map    true}}}}
```

My testscript:

```
(ns bar.testns
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)

(defn something [x]
  (* x 3))

(defn -main [& args]
  (println "foo"))

(set! *main-cli-fn* -main)
```

I run `cljs watch foo`, then in parallel `rlwrap cljs repl foo`:

```
cljs.user=> (require 'bar.testns :reload)
true
cljs.user=> (in-ns 'bar.testns)
nil
bar.testns=> (something 4)
8
bar.testns=> (something 4)
8
```

Between the two calls to `something` there was a recompile with a change that should return `12` but apparently it's not reloaded. I confirmed I'm running a278e6db3fcf72ee5fb4bb5bbe123fd2a5615ecf.

**Comment by shaunlebron** [comment]
@gnl thanks for the example!  I dumped it in a repo here to help make sure we're running the same thing: https://github.com/cljs/tool-repl-bug

I was unable to recreate the problem:

<img width="1319" alt="screen shot 2017-05-09 at 9 09 49 am" src="https://cloud.githubusercontent.com/assets/116838/25855109/dff47fa6-3497-11e7-85c0-ca3e33cb4a4c.png">

```
$ rlwrap cljs repl foo

(cljs) ClojureScript starting...

ClojureScript Node.js REPL server listening on 52380
To quit, type: :cljs/quit
cljs.user=> (require 'bar.testns)
true
cljs.user=> (in-ns 'bar.testns)
nil
bar.testns=> (something 4)
16
;; I save at this point with a new value in the `something` function
bar.testns=> (require 'bar.testns :reload)
true
bar.testns=> (something 4)
12
bar.testns=>
```

Can you confirm it again from the repo?  I'm not sure what could be happening.

**Comment by shaunlebron** [comment]
@gnl Sorry for not getting back to you very quickly on your question.  Were you able to solve this?

**Comment by gnl** [comment]
@shaunlebron Sorry about going dark, been a busy few weeks. It looks like there was a simple misunderstanding on my end - I assumed that the `(require ... :reload)` part would watch and auto-reload the recompiled namespaces (as in, you do it once at the beginning and that's it), rather than force a manual reload.

That would be nice, as my first attempts to make this work with Figwheel failed (I'll look into it again at some point when I have the time), but at least now we know that things work as designed. Thanks!

**Comment by shaunlebron** [comment]
oops, yeah, I failed to clarify that!

I suppose the watch task could send an update signal to the repl task to reload all previously `:reload`ed namespaces.  Not sure, will leave open for ideas.
